"use client";

import { useState } from "react";
import type { Demo, LedgerOutput } from "@/lib/counterexample";
import { Arrow } from "@/components/arrow";

function outputLabel(output: LedgerOutput) {
  return (
    output.status ??
    Object.entries(output.balances ?? {})
      .map(([account, value]) => `${account.toUpperCase()}: ${value}`)
      .join("  ")
  );
}

export function LabDemo({
  demos,
  initialDemoId,
}: {
  demos: Demo[];
  initialDemoId?: string;
}) {
  const initialIndex = Math.max(
    0,
    demos.findIndex((demo) => demo.id === initialDemoId),
  );
  const [selected, setSelected] = useState(initialIndex);
  const [position, setPosition] = useState(
    demos[initialIndex].steps.length - 1,
  );
  const demo = demos[selected];
  const step = demo.steps[position];
  const last = position === demo.steps.length - 1;
  return (
    <div className="demo">
      <div className="demo-heading">
        <span className="demo-label">COUNTEREXAMPLE / INTERACTIVE</span>
        <span className="demo-live">
          <span className="status-dot" />
          Oracle-backed
        </span>
      </div>
      <div className="demo-tabs" aria-label="Example scenario">
        {demos.map((item, index) => (
          <button
            key={item.id}
            type="button"
            aria-pressed={index === selected}
            onClick={() => {
              setSelected(index);
              setPosition(0);
            }}
          >
            <span>0{index + 1}</span>
            {["Retry", "Recovery", "Atomicity"][index]}
          </button>
        ))}
      </div>
      <div className="demo-body">
        <h2>{demo.title}</h2>
        <p className="demo-description">{demo.description}</p>
        <ol className="demo-steps">
          {demo.steps.map((item, index) => (
            <li key={index}>
              <button
                type="button"
                aria-pressed={index === position}
                onClick={() => setPosition(index)}
              >
                <span className="demo-step-number">{index + 1}</span>
                <span>{item.label}</span>
                {index === position && (
                  <span className="demo-step-here">←</span>
                )}
              </button>
            </li>
          ))}
        </ol>
        <div className="demo-code">
          <span>EVENT {String(position + 1).padStart(2, "0")}</span>
          <code>
            {step.event.op === "transfer" ? (
              <>
                {`transfer("${step.event.id}", ${step.event.from} → ${step.event.to}, ${step.event.amount})`}
                <small>expected_revision: {step.event.expected_revision}</small>
              </>
            ) : (
              `${step.event.op}()`
            )}
          </code>
        </div>
        <div className="demo-results" aria-live="polite" aria-atomic="true">
          <div>
            <span>Correct ledger</span>
            <strong className="text-green">{outputLabel(step.expected)}</strong>
          </div>
          <div className={step.differs ? "demo-mismatch" : ""}>
            <span>Faulty ledger</span>
            <strong>{outputLabel(step.actual)}</strong>
          </div>
        </div>
        <div className="demo-outcome" aria-live="polite">
          <span
            className={step.differs ? "demo-verdict exposed" : "demo-verdict"}
          >
            {step.differs ? "≠ Fault exposed" : "= Outputs agree"}
          </span>
          <button
            type="button"
            onClick={() => setPosition(last ? 0 : position + 1)}
          >
            {last ? "Replay" : "Next event"}
            <Arrow />
          </button>
        </div>
      </div>
      <p className="demo-caption">
        {last
          ? demo.explanation
          : "Follow the events, then compare the exact outputs. A useful test makes these ledgers disagree."}
      </p>
      <div className="demo-provenance">
        Hand-authored example · outputs generated by the benchmark code
      </div>
    </div>
  );
}
